# Default values for lsf master.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

cluster:
  master: default-spectrum-conductor
  pvc: conductor
  image:
    repository: mycluster.icp:8500/default/conductor-spark
    tag: 2.2

master:
  cpu: 1000m
  memory: 2048Mi

slave:
  cpu: 1000m
  memory: 2048Mi
  minReplicas: 1
  maxReplicasForAs: 3 
  targetCPUUtilizationPercentage: 50

license:
  key1: "enter license key"
  key2: "enter license key"

